# Generated by Django 4.1.3 on 2022-11-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studentid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
