# Generated by Django 4.1.3 on 2022-11-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='studentid',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
