# Generated by Django 4.1.3 on 2022-11-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_studentid_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('Computer Science', 'Bsc CS'), ('Information Technology', 'Bsc IT'), ('School of Computing', 'SOC'), ('Fullstack', 'FS')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=100),
        ),
    ]
